### ISSUE TITLE
Inserir versões na dependência no README e CMake

### ISSUE THREAD

**Issue by anderflash** [atkv/atkv2#56]
Só precisamos do CMake e GTK+
- CMake >= 3.1
- GTK+   >= 3.20

Se for um contribuidor do @kv, também é necessário instalar a API de TDD:
- CMocka >= 1.0

Só como referência, o GTK+ precisa desses pacotes e versões: 
   - Atk        >= 2.20
   - Pango  >= 1.40
   - Gdk-Pixbuf >= 2.34
   - GObject-introspection >= 1.48
   - GLib     >= 2.48
   - GCC     >= 4.9
   - ZLib      >= 1.2.8
   - PNG     >= 1.6
   - JPEG   >= 1.5

**Comment by hansbecc** [comment]
http://www.gtk.org/download/linux.php

**Comment by anderflash** [comment]
Legal, simples e efetivo. :)
